module.exports =
['Bedřichovické hody 2022',
'Zakončení Semestru / Fléda',
'Oldies | UB Club',
'EXIT At The Castle [Open Air]',
'Strážnický košt vín',
'CEJH CONGRESS 2022',
'Krumlovský Majáles 2022',
'EDM | UB club | Rousínov',
'Jsem orlovský Leonard Cohen',
'Velikonoční Party Otaslavice',
'POHÁDKOLAND 2022 - SLAVKOV U BRNA',
'Slavnosti Olomouc 2022',
'Brněnské Pyvo - Mezinárodní',
'Základy záchrany na tekoucí vodě',
'Burčákový pochod 2022',
'Pandemicon 2022',
'Deskovky v dubnu I. (EnjoyTeam prod.)',
'Jak pečovat o dětské duševní zdraví',
'Jarní trhy',
'VELIKONOČNÍ MEJDAN @Bobycentrum, LaGrotta',
'Brněnský Majáles 2022',
'Motovíkend 2022',
'Šenkýř Motorsport Slovakiaring Trackday - 25.08.2022',
'ILEGAL TUNING PARTY vol.2',
'14. Retroden',
'Florbalový turnaj Orel cup 2022',
'Webinář - Modernizace výtahu – jak ušetřit čas, energii i peníze',
'BlackJack - Ořechov, pouťová',
'MMAA Aréna Cup 66',
'Velikonoční Párty v Syndicate',
'FAKULTY ONLINE III. - Kam je čas se v dubnu přihlásit?',
'Viktor Sheen - Olomouc Sklub Open Air 2022',
'Velikonoční zábava',
'SHEFA | 14.4. ZELENÝ ČTVRTEK | PEKLO VYŠKOV',
'SMACK (BEL) - 7.nebe Brno - Sobota',
'Pouťová zábava',
'Hody Rousínov',
'SDK Pustiměř - Hasičská výstava',
'Tuning Vyškov',
'DJ Boris, Velké Němčice',
]